linters-settings:
  depguard:
    list-type: blacklist
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    # disabled-checks:
    #   - dupImport # https://github.com/go-critic/go-critic/issues/845
    #   - ifElseChain
    #   - octalLiteral
    #   - whyNoLint
    #   - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  lll:
    line-length: 80
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    # - contextcheck
    # - exhaustruct
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    # - goerr113
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: .*admin/bindatafs/.*
      linters:
        - errcheck
        - lll
        - godox
        - gosec
        - gofmt
        - gosec
        - gochecknoglobals
        - gocognit
        - gochecknoinits
        - goconst
        - golint
        - gosimple
        - cyclop
        - forbidigo
        - goerr113
        - ireturn
        - nlreturn
        - nestif
        - nonamedreturns
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - noctx
    - path: .*mocks/.*
      linters:
        - forcetypeassert
    - path: app_test\.go
      linters:
        - gomnd
        - dupl
        - gocritic
    - linters:
        - lll
      source: "`.*"
