log_path: logs/app.test.log
server_log_path: logs/server.test.log
is_prod: false
database_type: sqlite3
database_uri: ":memory:"
secret: secret_password_test
session_name: vishleva_admin_session_test
session_key: vishleva_user_id_test
order_statuses:
  - not_confirmed
  - open
  - closed
order_sources:
  - manual
  - online

#paths
admin_path: "admin"
login_path: "/auth/login"
logout_path: "/auth/logout"
#messenger email
messenger_email_from: "form@host.com"
messenger_email_host: "smtp.host.com"
messenger_email_port: 587
messenger_email_login: "test@host.com"
messenger_email_password: "password"
messenger_telegram_token: "token"
messenger_vk_token: "token"
