log_path: logs/app.log
server_log_path: logs/server.log
is_prod: true
database_type: postgres
database_uri: host=vishleva-backend-postgres port=5432 user=postgres dbname=vishleva_backend password=postgres sslmode=disable TimeZone=UTC
secret: secret_password
timezone: UTC
order_statuses:
  - not_confirmed
  - open
  - closed
order_sources:
  - manual
  - online

#paths
admin_path: "admin"
login_path: "/auth/login"
logout_path: "/auth/logout"

#messenger email
messenger_email_from: "form@host.com"
messenger_email_host: "smtp.host.com"
messenger_email_port: 587
messenger_email_login: "test@host.com"
messenger_email_password: "password"

#messenger telegram (BotFather)
messenger_telegram_token: "token"

#messenger vk (community token. example: https://vk.com/clubXXX?act=tokens)
messenger_vk_token: "token"
