package mocks

import (
	"github.com/stretchr/testify/mock"
)

// ContactsGetter is an autogenerated mock type for the ContactsGetter type.
type ContactsGetter struct {
	mock.Mock
}

// GetEmail is method mock.
func (s *ContactsGetter) GetEmail() string {
	arg := s.Called()

	return arg.Get(0).(string)
}

// GetTelegram is method mock.
func (s *ContactsGetter) GetTelegram() string {
	arg := s.Called()

	return arg.Get(0).(string)
}

// GetVK is method mock.
func (s *ContactsGetter) GetVK() string {
	arg := s.Called()

	return arg.Get(0).(string)
}
