// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	api "github.com/SevereCloud/vksdk/v2/api"

	mock "github.com/stretchr/testify/mock"
)

// VkAPISender is an autogenerated mock type for the VkAPISender type
type VkAPISender struct {
	mock.Mock
}

// MessagesSend provides a mock function with given fields: b
func (_m *VkAPISender) MessagesSend(b api.Params) (int, error) {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for MessagesSend")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(api.Params) (int, error)); ok {
		return rf(b)
	}
	if rf, ok := ret.Get(0).(func(api.Params) int); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(api.Params) error); ok {
		r1 = rf(b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVkAPISender creates a new instance of VkAPISender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVkAPISender(t interface {
	mock.TestingT
	Cleanup(func())
}) *VkAPISender {
	mock := &VkAPISender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
